### ISSUE TITLE
editor-routes

### ISSUE THREAD

**Issue by JacqMcQ** [JacqMcQ/Reader-Reply#11]
editor.handlebars, editor-routes, editor.js, event listeners , test , make sure displayed on dashboard view.

**Comment by bldambtn** [comment]
<div class="body">
        <div class="column-1">
            <form>
                <label for="title">Title</label>
                <input type="text" id="title" name="title">

                <label for="existing-works">Add to Existing Works</label>
                <select id="existing-works" name="existing-works">
                    <option value="">Select an existing work</option>
                    
                </select>

                <label for="content">Content</label>
                <textarea id="content" name="content" rows="10"></textarea>

                <div class="form-buttons">
                    <button id="save-button" type="button">Save</button>
                    <button id="edit-button" type="button">Edit</button>
                    <button id="post-button" type="button">Post</button>
                    <button id="delete-button" type="button">
                        <i class="fa-solid fa-trash-can"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="column-2">
            <div class="comments-section">
                <h2>Comments</h2>
                
                <p id="placeholder">Comments will display here</p>
                
                <div class="comment">
                    <p>Great work on this chapter!</p>
                    <p class="username">- JohnDoe</p>
                </div>
                <div class="comment">
                    <p>Really enjoyed reading this. Looking forward to more!</p>
                    <p class="username">- JaneSmith</p>
                </div>
                
                <a href="#view-more" class="view-more">View More</a>               
            </div>
        </div>
    </div>

**Comment by JacqMcQ** [comment]
Updated dashboard.handlebars

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dashboard</title>
  <link rel="stylesheet" href="/public/assets/style.css">
</head>
<body>
<div id="dashboard" class="body">
  <div class="dashboard-container">
    <div class="column create-new">
      <button id="create-new-btn" class="action-btn">Create New</button>
      <div class="quote-container">Inspirational quote here...</div>
    </div>

    <div class="column continue-reading">
      <h2>Continue Reading</h2>
      
      <p><a href="#">Story Title 1</a></p>
      <p><a href="#">Story Title 2</a></p>
      <a href="#" class="view-more">View More</a>
    </div>

    <div class="column continue-writing">
      <h2>Continue Writing</h2>
  
      <div class="story-item">
        <p><a href="#">Story Title 1</a></p>
        <p class="comment">- Recent comment here...</p>
      </div>
      <div class="story-item">
        <p><a href="#">Story Title 2</a></p>
        <p class="comment">- Recent comment here...</p>
      </div>
      <a href="#" class="view-more">View More</a>
    </div>
  </div>
</div>
 <script src="/js/dashboard.js"></script>
</body>
</html>
